rootLogger: INFO,console,file

logger:
   hadoo: INFO,hadoo
   hotdocs: INFO,hotdocs
   query: INFO,query
   org.apache: INFO

additivity:
   hadoo: false
   hotdocs: false
   query: false


appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
  hadoo:
    type: dailyRollingFile
    file: ${path.logs}/hadoo.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}] %m%n"
  hotdocs:
    type: dailyRollingFile
    file: ${path.logs}/hotdocs.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}] %m%n"
  query:
      type: dailyRollingFile
      file: ${path.logs}/query.log
      datePattern: "'.'yyyy-MM-dd"
      layout:
        type: pattern
        conversionPattern: "[%d{ISO8601}] %m%n"

  file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
      